on:
  push: # Run this action when push event triggers.
    branches: # Run this action on specified branches
      - basic-framework # Branch name

name: Run BackstopJS test cases # Name of the action
jobs:
  Run-BackstopJS-TestCase:
    name: Run BackstopJS test Case #
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install BackstopJS Dependecy 
      run: npm install
    
    - name: Create reference screenshot from source site
      run: npm run reference

    - name: Run the test(It will take the screenshot of the given site and will test against reference screenshot)
      run: npm run test
    
   # - name: Archive HTML Report
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: html-report
    #     path: backstop_data/

    - name: Archive HTML Report 
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: html-report
        path: ./backstop_data/
    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master
      

